create or replace PROCEDURE "BANLE_TIMKIEM_BOHANG_MAHANG" 
(
  P_MADONVI IN VARCHAR2 ,
  P_TUKHOA IN VARCHAR2,
  P_SUDUNG_TIMKIEM_ALL IN NUMBER,
  P_DIEUKIENCHON IN NUMBER,
  CURSOR_RESULT OUT SYS_REFCURSOR
) AS 
  QUERY_SELECT VARCHAR2(3000);
  T_LOAITIMKIEM VARCHAR2(20) := '';
  TEXT_IS_NUMBER NUMBER(18,2) := 0;
  IS_CONTAIN_UNITCODE VARCHAR2(2):='';
BEGIN
  SELECT IS_NUMBER(P_TUKHOA) INTO TEXT_IS_NUMBER FROM DUAL;
  BEGIN 
      SELECT * INTO IS_CONTAIN_UNITCODE FROM DUAL WHERE REGEXP_REPLACE(P_TUKHOA, '[^ -~]', '@') LIKE '%@%';
      EXCEPTION WHEN NO_DATA_FOUND
      THEN IS_CONTAIN_UNITCODE := '';
  END;
  IF P_SUDUNG_TIMKIEM_ALL = 1 THEN
      IF LENGTH(P_TUKHOA) = 13 AND TEXT_IS_NUMBER = 1 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'BARCODE';
      END IF;
      IF LENGTH(P_TUKHOA) = 7 AND SUBSTR(P_TUKHOA,0,2) <> 'BH' AND TEXT_IS_NUMBER = 0 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'MAVATTU';
      END IF;
      IF IS_CONTAIN_UNITCODE = 'X' 
        THEN T_LOAITIMKIEM := 'TENVATTU';
      END IF; 
      IF LENGTH(P_TUKHOA) = 4 AND TEXT_IS_NUMBER = 1 AND (IS_CONTAIN_UNITCODE IS NULL OR IS_CONTAIN_UNITCODE = '') 
        THEN T_LOAITIMKIEM := 'MACANDIENTU';
      END IF; 
      IF SUBSTR(P_TUKHOA,0,2) = 'BH' 
        THEN T_LOAITIMKIEM := 'BOHANG';
      END IF;
  ELSE
      IF P_DIEUKIENCHON = 0
        THEN T_LOAITIMKIEM := 'MAVATTU';
      END IF;
      IF P_DIEUKIENCHON = 1
        THEN T_LOAITIMKIEM := 'BARCODE';
      END IF;
      IF P_DIEUKIENCHON = 2
        THEN T_LOAITIMKIEM := 'MACANDIENTU';
      END IF; 
      IF P_DIEUKIENCHON = 3
        THEN T_LOAITIMKIEM := 'TENVATTU';
      END IF; 
      IF P_DIEUKIENCHON = 4
        THEN T_LOAITIMKIEM := 'BOHANG';
      END IF; 
      IF P_DIEUKIENCHON = 5
        THEN T_LOAITIMKIEM := 'MAHANGTRONGBO';
      END IF;
      IF P_DIEUKIENCHON = 6
        THEN T_LOAITIMKIEM := 'GIABANLECOVAT';
      END IF; 
  END IF;
IF P_SUDUNG_TIMKIEM_ALL = 1 THEN
    IF T_LOAITIMKIEM = 'BARCODE' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.BARCODE LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'MAVATTU' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.MAVATTU LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'TENVATTU' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND UPPER(a.TENVATTU) LIKE N''%'||UPPER(P_TUKHOA)||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'MACANDIENTU' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.ITEMCODE = '''||P_TUKHOA||''' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'BOHANG' THEN
        QUERY_SELECT := 'SELECT b.MABOHANG AS MAVATTU,b.MAHANG AS MAKHAC,c.TENHANG AS TENVATTU,c.MALOAIVATTU,c.MANHOMVATTU,
                        c.DONVITINH,c.MAKHACHHANG AS MANHACUNGCAP,c.TENNHACUNGCAP,
                        c.MAKEHANG,c.GIABANLEVAT,c.ITEMCODE,c.BARCODE
                        FROM DM_BOHANG a INNER JOIN DM_BOHANGCHITIET b ON  a.MABOHANG = b.MABOHANG INNER JOIN V_VATTU_GIABAN c ON
                         c.MAVATTU = b.MAHANG AND c.UNITCODE = '''||P_MADONVI||''' AND b.MABOHANG LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'MAHANGTRONGBO' THEN
        QUERY_SELECT := 'SELECT b.MABOHANG AS MAVATTU,b.MAHANG AS MAKHAC,c.TENHANG AS TENVATTU,c.MALOAIVATTU,c.MANHOMVATTU,
                        c.DONVITINH,c.MAKHACHHANG AS MANHACUNGCAP,c.TENNHACUNGCAP,
                        c.MAKEHANG,c.GIABANLEVAT,c.ITEMCODE,c.BARCODE
                        FROM DM_BOHANG a INNER JOIN DM_BOHANGCHITIET b ON  a.MABOHANG = b.MABOHANG INNER JOIN V_VATTU_GIABAN c ON
                         c.MAVATTU = b.MAHANG AND c.UNITCODE = '''||P_MADONVI||''' AND b.MAHANG LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'GIABANLECOVAT' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.GIABANLEVAT = '||P_TUKHOA||' AND ROWNUM < 201';
        ELSE 
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.MAVATTU LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
    END IF;
ELSE
    IF T_LOAITIMKIEM = 'BARCODE' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.BARCODE LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'MAVATTU' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.MAVATTU LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'TENVATTU' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND UPPER(a.TENVATTU) LIKE N''%'||UPPER(P_TUKHOA)||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'MACANDIENTU' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.ITEMCODE = '''||P_TUKHOA||''' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'BOHANG' THEN
        QUERY_SELECT := 'SELECT b.MABOHANG AS MAVATTU,b.MAHANG AS MAKHAC,c.TENHANG AS TENVATTU,c.MALOAIVATTU,c.MANHOMVATTU,
                        c.DONVITINH,c.MAKHACHHANG AS MANHACUNGCAP,c.TENNHACUNGCAP,
                        c.MAKEHANG,c.GIABANLEVAT,c.ITEMCODE,c.BARCODE
                        FROM DM_BOHANG a INNER JOIN DM_BOHANGCHITIET b ON  a.MABOHANG = b.MABOHANG INNER JOIN V_VATTU_GIABAN c ON
                         c.MAVATTU = b.MAHANG AND c.UNITCODE = '''||P_MADONVI||''' AND b.MABOHANG LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'MAHANGTRONGBO' THEN
        QUERY_SELECT := 'SELECT b.MABOHANG AS MAVATTU,b.MAHANG AS MAKHAC,c.TENHANG AS TENVATTU,c.MALOAIVATTU,c.MANHOMVATTU,
                        c.DONVITINH,c.MAKHACHHANG AS MANHACUNGCAP,c.TENNHACUNGCAP,
                        c.MAKEHANG,c.GIABANLEVAT,c.ITEMCODE,c.BARCODE
                        FROM DM_BOHANG a INNER JOIN DM_BOHANGCHITIET b ON  a.MABOHANG = b.MABOHANG INNER JOIN V_VATTU_GIABAN c ON
                         c.MAVATTU = b.MAHANG AND c.UNITCODE = '''||P_MADONVI||''' AND b.MAHANG LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
        ELSIF T_LOAITIMKIEM = 'GIABANLECOVAT' THEN
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.GIABANLEVAT = '||P_TUKHOA||' AND ROWNUM < 201';
        ELSE 
        QUERY_SELECT := 'SELECT a.MAVATTU,a.MAKHAC,a.TENVATTU,a.MALOAIVATTU,a.MANHOMVATTU,
                        a.DONVITINH,a.MAKHACHHANG AS MANHACUNGCAP,a.TENNHACUNGCAP,
                        a.MAKEHANG,a.GIABANLEVAT,a.ITEMCODE,a.BARCODE
                        FROM V_VATTU_GIABAN a WHERE UNITCODE = '''||P_MADONVI||''' AND a.MAVATTU LIKE ''%'||P_TUKHOA||'%'' AND ROWNUM < 201';
    END IF;
END IF;
    DBMS_OUTPUT.PUT_LINE('QUERY_SELECT:'||QUERY_SELECT);
  BEGIN
  OPEN CURSOR_RESULT FOR QUERY_SELECT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.put_line ('NO_DATA_FOUND');  
       WHEN OTHERS THEN
     DBMS_OUTPUT.put_line (SQLERRM);  
  END;
END BANLE_TIMKIEM_BOHANG_MAHANG;
 
 